# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

schedules:
- cron: "0 * * * *"
  displayName: Run Script Every Hour
  branches:
    include:
    - Sinawo-Mod

trigger:
  branches:
    include:
    - '*'
pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'  # Replace 'x' with the desired Python version
  displayName: 'Use Python'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'
  workingDirectory: $(System.DefaultWorkingDirectory)
- script: |
    python ssms-scraper.py
  displayName: 'Run ssms-scraper.py'
  workingDirectory: $(System.DefaultWorkingDirectory)