name: Automated Pipeline

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - master

jobs:
  RunScript:
    runs-on: ubuntu-latest
    timeout-minutes: 720

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install pyodbc
          pip install regex
          pip install lxml

      - name: Run ssms-scraper.py
        run: python ssms-scraper.py

